name: K6 Full Performance Test

on:
  workflow_dispatch:      # cho phép chạy thủ công
  push:
    branches: [ "main" ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Backend Load Test (GET, POST, PUT)
        run: |
          docker run -v $PWD:/scripts -w /scripts grafana/k6 run be/get_products_load_test.js
          docker run -v $PWD:/scripts -w /scripts grafana/k6 run be/post_products_stress_test.js
          docker run -v $PWD:/scripts -w /scripts grafana/k6 run be/put_products_load_test.js

  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Frontend Stress Tests (Home + Full)
        run: |
          docker run -v $PWD:/scripts -w /scripts grafana/k6 run fe/home_spike_test.js
          docker run -v $PWD:/scripts -w /scripts grafana/k6 run fe/stress_test.js
