name: K6 Full Performance Test

on:
  workflow_dispatch:      # cho phép chạy thủ công
  push:
    branches: [ "main" ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install k6
        run: |
          curl -s https://dl.k6.io/releases/latest/k6-v0.51.0-linux-amd64.deb -o k6.deb
          sudo dpkg -i k6.deb
      - name: Run Backend Load Test
        run: |
          k6 run be/get_products_load_test.js
          k6 run be/post_products_stress_test.js
          k6 run be/put_products_load_test.js

  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install k6
        run: |
          sudo apt-get update
          sudo apt-get install -y k6
      - name: Run Frontend Stress Test
        run: |
          k6 run fe/home_spike_test.js
          k6 run fe/stress_test.js